## Realizando as importações

In [87]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

## Importando os dados de tumores para usar como base de treinamento 

In [99]:
previsores = pd.read_csv('entradas-breast.csv',  sep=',', encoding = 'ISO-8859-1').values
classe = pd.read_csv('saidas-breast.csv').values

In [100]:
type(previsores)
previsores

array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02, ...,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
       [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02, ...,
          1.86000000e+02,   2.75000000e+02,   8.90200000e-02],
       [  1.96900000e+01,   2.12500000e+01,   1.30000000e+02, ...,
          2.43000000e+02,   3.61300000e-01,   8.75800000e-02],
       ..., 
       [  1.66000000e+01,   2.80800000e+01,   1.08300000e+02, ...,
          1.41800000e-01,   2.21800000e-01,   7.82000000e-02],
       [  2.06000000e+01,   2.93300000e+01,   1.40100000e+02, ...,
          2.65000000e+02,   4.08700000e-01,   1.24000000e+02],
       [  7.76000000e+00,   2.45400000e+01,   4.79200000e+01, ...,
          0.00000000e+00,   2.87100000e-01,   7.03900000e-02]])

## Criando  a base de dados para treinamento e teste
### Será utilizado 25% da base de dados para testes utilizando o metodo train_test_split do sklearn

In [101]:
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25)

# Criando os neuronios 
## Usando Keras, criamos 30 neuronios na camada de entrada, uma pra cada particularidade dos dados de cancer
## Usando 16 neuronios na camada oculta, formula (30 entrada + 1 saida / 2)
## Usando 1 neuronio na camada de saida para resultados falsos ou verdadeiros

In [102]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [118]:
classificador = Sequential()

In [119]:
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform', input_dim=30))

In [120]:
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))

In [121]:
classificador.add(Dense(units=1, activation='sigmoid'))

In [122]:
otimizador = keras.optimizers.Adam(lr=0.001,  decay=0.0001,clipvalue = 0.5)

In [123]:
classificador.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])

In [124]:
classificador.fit(previsores_treinamento, classe_treinamento, batch_size=10, epochs=100)

Epoch 1/100
426/426 [==============================] - 0s - loss: 0.8847 - binary_accuracy: 0.6385     
Epoch 2/100
426/426 [==============================] - 0s - loss: 0.4978 - binary_accuracy: 0.7371     
Epoch 3/100
426/426 [==============================] - 0s - loss: 0.5656 - binary_accuracy: 0.7324     
Epoch 4/100
426/426 [==============================] - 0s - loss: 0.4332 - binary_accuracy: 0.7793     
Epoch 5/100
426/426 [==============================] - 0s - loss: 0.5812 - binary_accuracy: 0.7535     
Epoch 6/100
426/426 [==============================] - 0s - loss: 0.4439 - binary_accuracy: 0.8005     
Epoch 7/100
426/426 [==============================] - 0s - loss: 0.3741 - binary_accuracy: 0.8333     
Epoch 8/100
426/426 [==============================] - 0s - loss: 0.4378 - binary_accuracy: 0.8169     
Epoch 9/100
426/426 [==============================] - 0s - loss: 0.4427 - binary_accuracy: 0.8263     
Epoch 10/100
426/426 [==============================] - 0s - los

426/426 [==============================] - 0s - loss: 0.5158 - binary_accuracy: 0.8732     
Epoch 80/100
426/426 [==============================] - 0s - loss: 0.3839 - binary_accuracy: 0.8662     
Epoch 81/100
426/426 [==============================] - 0s - loss: 0.4418 - binary_accuracy: 0.8873     
Epoch 82/100
426/426 [==============================] - 0s - loss: 0.4064 - binary_accuracy: 0.8568     
Epoch 83/100
426/426 [==============================] - 0s - loss: 0.4214 - binary_accuracy: 0.8732     
Epoch 84/100
426/426 [==============================] - 0s - loss: 0.5278 - binary_accuracy: 0.8498     
Epoch 85/100
426/426 [==============================] - 0s - loss: 0.5560 - binary_accuracy: 0.8545     
Epoch 86/100
426/426 [==============================] - 0s - loss: 0.5689 - binary_accuracy: 0.8638     
Epoch 87/100
426/426 [==============================] - 0s - loss: 0.5273 - binary_accuracy: 0.8685     
Epoch 88/100
426/426 [==============================] - 0s - loss: 0

In [125]:

previsores = classificador.predict(previsores_teste)
previsores = previsores > 0.5

array([[False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [134]:
pesos0 = classificador.layers[0].get_weights()
pesos1 = classificador.layers[1].get_weights()
pesos2 = classificador.layers[2].get_weights()
pesos2

[array([[-0.51017261],
        [-0.12652352],
        [-0.2243275 ],
        [-0.33446461],
        [ 0.30252123],
        [ 0.16985671],
        [-0.34633124],
        [-0.07186133],
        [ 0.3570925 ],
        [ 0.43659183],
        [-0.49752784],
        [ 0.09497985],
        [-0.46991697],
        [-0.50316727],
        [-0.19957291],
        [-0.21722899]], dtype=float32), array([ 0.31314957], dtype=float32)]

In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [128]:
precisao = accuracy_score(classe_teste, previsores)
precisao

0.85314685314685312

In [129]:
matrix_confusion = confusion_matrix(classe_teste, previsores)
matrix_confusion

array([[42, 11],
       [10, 80]])

In [130]:
resultado = classificador.evaluate(previsores_teste, classe_teste)
resultado

 32/143 [=====>........................] - ETA: 0s

[1.0210565609948619, 0.85314685356366882]